version: '3.8'

services:
  api:
    build: .
    volumes:
      - ./:/code:Z
      - static:/code/static
      - media:/code/media
    networks:
      - nginx
      - db
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=f37^gjd)atl%!r#$$e-js#^o!puw+2@71sp^n=au=9p5easrx)y
      - DEBUG=False

  nginx:
    image: nginx:1.13
    ports:
        - 8000:80
    volumes:
        - ./config/nginx/conf.d:/etc/nginx/conf.d
        - static:/code/static
        - media:/code/media
    depends_on:
        - api
    networks:
      - nginx

  db:
    image: postgres:11
    restart: unless-stopped
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

networks:
  nginx:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres_data:
  static:
  media:
